In [1]:
import tensorflow as tf
#print(tf.version)

In [2]:
string = tf.Variable('dis is string',tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567,tf.float64)

In [3]:
rank1_tensor = tf.Variable(['Test','Ok','Dog'],tf.string)
rank2_tensor = tf.Variable([['test','dog','3rdele'],['2nd','level','6']],tf.string)

In [4]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
rank1_tensor.shape

TensorShape([3])

In [6]:
rank2_tensor.shape

TensorShape([2, 3])

In [7]:
tensor1 = tf.ones([1,2,3])
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [8]:
tensor1 = [[[1,2,3],[4,5,6]]]
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

[[[1, 2, 3], [4, 5, 6]]]
tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]], shape=(2, 3, 1), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [9]:
#with tf.compat.v1.Session() as sess:
#    tensor.eval()

tf.compat.v1.Session() instead of tf.Session()

### Playing

In [10]:
t = tf.zeros([5,5,5,5])
tr = tf.reshape(t,[-1,125])